export const AppConstants = {
  apiUrl: 'https://localhost:5001/',
  getSummaryOfWorkHours: 'Dashboard/GetSummaryOfWorkHours',
  getSummaryOfWorkHoursReport: 'Report/GetSummaryOfWorkHoursReport',
  getDailyAttendanceStatus: 'Dashboard/GetDailyAttendanceStatus',
  getDailyAttendance: 'Dashboard/GetDailyAttendance',
  getDailyAttendanceReport: 'Report/GetDailyAttendanceReport',
  getLateLogin: 'Dashboard/LateLogin',
  getLateLoginReport: 'Report/GetLateLoginReport',
  getEarlyLogout: 'Dashboard/EarlyLogout',
  getEarlyLogoutReport: 'Report/GetEarlyLogoutReport',
  getEmpWorkedOnWeekend: 'Dashboard/GetEmpWorkedOnWeekend',
  getEmpWorkedOnWeekendReport: 'Report/GetEmpWorkedOnWeekendReport',
  getFilterDropdowns: 'Dashboard/GetFilterDropdowns',
  getOvertimeDetails: 'Dashboard/GetOvertimeDetails',
  getAvgOTHoursByAge: 'Dashboard/GetAvgOTHoursByAge',
  getAvgOTHoursByAgeReport: 'Report/GetAvgOTHoursByAgeReport',
  getTotalHoursWorked: 'Dashboard/GetTotalHoursWorked',
  getAvgHoursPerEmp: 'Dashboard/GetAvgHoursPerEmp',
  getTotalDeviationMinutes: 'Dashboard/GetTotalDeviationMinutes',
  getTotalDeviationMinutesReport: 'Report/GetTotalDeviationMinutesReport',
  getLateLoginHours: 'Dashboard/GetLateLoginHours',
  getEarlyLogoutHours: 'Dashboard/GetEarlyLogoutHours',
  getPenalizationMetrics: 'Dashboard/GetPenalizationMetrics',
  getPenalizationMetricsReport: 'Report/GetPenalizationMetricsReport',
  getEarlyLogoutMetrics: 'Dashboard/GetEarlyLogoutMetrics',
  getEarlyLogoutMetricsReport: 'Report/GetEarlyLogoutMetricsReport',
  getLateLogintMetrics: 'Dashboard/GetLateLogintMetrics',
  getLateLogintMetricsReport: 'Report/GetLateLoginMetricsReport',
  getPenalizationInstances: 'Dashboard/GetPenalizationInstances',
  getPenalizationInstancesReport: 'Report/GetPenalizationInstancesReport',
  getWeeklyOvertime: 'Dashboard/GetWeeklyOvertime',
  getWeeklyOvertimeReport: 'Report/GetWeeklyOTReport',
  getTargetVsActualWorkDays:'Dashboard/GetTargetVsActualWorkDays',
  getTargetVsActualWorkDaysReport:'Report/GetTargetVsActualWorkHrsReport',
  getAllDashboardGraphs:'Dashboard/GetAllDashboardGraphs',
  saveGraphConfigurations:'Dashboard/SaveGraphConfigurations',
  postSaveFilters: 'Dashboard/SaveFilters',
  postSaveCloneReport: 'Dashboard/SaveCloneReport',
  postGetOvertimeReport: 'Report/GetOvertimeReport',
  postDailyAttendanceStatusReport: 'Report/GetDailyAttendanceStatusReport',
};
